# Generated by Django 6.1.1 on 2026-09-06 21:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('class', 'Class'), ('gym', 'Fitness'), ('event', 'Event')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('professor', models.CharField(blank=True, max_length=150)),
                ('room', models.CharField(blank=True, max_length=150)),
                ('activity', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.CharField(blank=True, help_text='Comma-separated: Mon,Wed,Fri', max_length=27)),
                ('week_type', models.CharField(choices=[('both', 'Every week'), ('A', 'Week A'), ('B', 'Week B')], default='both', max_length=4)),
                ('is_one_time', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('color', models.CharField(default='#3E7BFA', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='system', max_length=10)),
                ('hour_start', models.PositiveSmallIntegerField(default=7)),
                ('hour_end', models.PositiveSmallIntegerField(default=22)),
                ('week_a_anchor', models.DateField(default=datetime.date(2026, 1, 5))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['done', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeekOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_monday', models.DateField()),
                ('week_type', models.CharField(choices=[('A', 'Week A'), ('B', 'Week B')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'week_monday')},
            },
        ),
    ]
